In [3]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("sales_data.csv")
df.head()

         Date     Product     Category Region  Quantity  Price  Total_Sales
0  2024-01-01      Laptop  Electronics   West         2  50000       100000
1  2024-01-02      Mobile  Electronics  North         3  20000        60000
2  2024-01-03  Headphones  Accessories  South         5   2000        10000
3  2024-01-04    Keyboard  Accessories   East         4   1500         6000
4  2024-01-05       Mouse  Accessories   West         6    800         4800

In [4]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         10 non-null     object
 1   Product      10 non-null     object
 2   Category     10 non-null     object
 3   Region       10 non-null     object
 4   Quantity     10 non-null     int64
 5   Price        10 non-null     int64
 6   Total_Sales  10 non-null     int64
dtypes: int64(3), object(4)
memory usage: 472.0+ bytes

       Quantity         Price    Total_Sales
count  10.00000     10.000000      10.000000
mean    2.90000  19130.000000   35180.000000
std     1.66333  19079.718726   32220.966259
min     1.00000    800.000000    4800.000000
25%     2.00000   2000.000000    7000.000000
50%     2.50000  17500.000000   27500.000000
75%     3.75000  27500.000000   57500.000000
max     6.00000  50000.000000  100000.000000